array set __opts {
    BackLog                 {20}
    BalloonHelp             {1}
    FrequencyDefault        {100.0}
    FrequencyList           {}
    InitDiagSizeX           {400}
    InitDiagSizeY           {300}
    MaxInterval             {50}
    PollInterval            {20}
    Position,.              {516x531+1074+464}
    Position,.dataframe0    {1920x1017+570+72}
    PrefQuants              {
	Implicit T Time Time.Global Kl15SW SC.State SC.Start.No Brake.pMC DM.Gas DM.Clutch DM.Brake DM.GearNo DM.BrakePark DM.Shifting DM.Steer.Ang DM.Steer.Trq DM.FBrake DM.Steer.AngPos DM.Steer.Trq DM.Steer.Ang TGlob Time.Global PT.Engine.rotv DM.BrakePedal PT.Engine_rotv PT.Engine.Trq Steer.WhlAng Steer.WhlTrq Car.SimPhase Car.v Car.sRoad Car.vFL Car.vFR Car.vRL Car.vRR Car.ax Car.ay Car.az Car.Yaw Car.YawRate Car.Pitch Car.PitchVel Car.Roll Car.RollVel Car.SSAngle Car.CFL.q0 Car.CFR.q0 Car.CRL.q0 Car.CRR.q0 Car.CFL.tx Car.CFR.tx Car.CRL.tx Car.CRR.tx Car.CFL.ty Car.CFR.ty Car.CRL.ty Car.CRR.ty Car.CFL.tz Car.CFR.tz Car.CRL.tz Car.CRR.tz Car.CFL.rx Car.CFR.rx Car.CRL.rx Car.CRR.rx Car.CFL.ry Car.CFR.ry Car.CRL.ry Car.CRR.ry Car.CFL.rz Car.CFR.rz Car.CRL.rz Car.CRR.rz Car.SpringFL.Frc Car.SpringFR.Frc Car.SpringRL.Frc Car.SpringRR.Frc Car.SpringFL.l Car.SpringFR.l Car.SpringRL.l Car.SpringRR.l Car.StabiFL.Frc Car.StabiFR.Frc Car.StabiRL.Frc Car.StabiRR.Frc Car.StabiFL.l Car.StabiFR.l Car.StabiRL.l Car.StabiRR.l Car.DampFL.Frc Car.DampFR.Frc Car.DampRL.Frc Car.DampRR.Frc Car.DampFL.v Car.DampFR.v Car.DampRL.v Car.DampRR.v Car.FxFL Car.FxFR Car.FxRL Car.FxRR Car.FyFL Car.FyFR Car.FyRL Car.FyRR Car.FzFL Car.FzFR Car.FzRL Car.FzRR Car.LongSlipFL Car.LongSlipFR Car.LongSlipRL Car.LongSlipRR Car.SlipAngleFL Car.SlipAngleFR Car.SlipAngleRL Car.SlipAngleRR Car.ToeFL Car.ToeFR Car.ToeRL Car.ToeRR Car.TrqAlignFL Car.TrqAlignFR Car.TrqAlignRL Car.TrqAlignRR Brake.pFL_FL Brake.pFR_FL Brake.pRL_FL Brake.pRR_FL Brake.Trq_FL_tot Brake.Trq_FR_tot Brake.Trq_RL_tot Brake.Trq_RR_tot PT.WFL.rotv PT.WFR.rotv PT.WRL.rotv PT.WRR.rotv PT.WFL.Trq_Drive PT.WFR.Trq_Drive PT.WRL.Trq_Drive PT.WRR.Trq_Drive PT.WFL.Trq_B2W PT.WFR.Trq_B2W PT.WRL.Trq_B2W PT.WRR.Trq_B2W MC.SimPhase MC.v MC.sRoad MC.vFL MC.vFR MC.vRL MC.vRR MC.ax MC.ay MC.az MC.Yaw MC.YawRate MC.Pitch MC.PitchVel MC.Roll MC.RollVel MC.SSAngle MC.CFL.q0 MC.CFR.q0 MC.CRL.q0 MC.CRR.q0 MC.CFL.tx MC.CFR.tx MC.CRL.tx MC.CRR.tx MC.CFL.ty MC.CFR.ty MC.CRL.ty MC.CRR.ty MC.CFL.tz MC.CFR.tz MC.CRL.tz MC.CRR.tz MC.CFL.rx MC.CFR.rx MC.CRL.rx MC.CRR.rx MC.CFL.ry MC.CFR.ry MC.CRL.ry MC.CRR.ry MC.CFL.rz MC.CFR.rz MC.CRL.rz MC.CRR.rz MC.SpringFL.Frc MC.SpringFR.Frc MC.SpringRL.Frc MC.SpringRR.Frc MC.SpringFL.l MC.SpringFR.l MC.SpringRL.l MC.SpringRR.l MC.StabiFL.Frc MC.StabiFR.Frc MC.StabiRL.Frc MC.StabiRR.Frc MC.StabiFL.l MC.StabiFR.l MC.StabiRL.l MC.StabiRR.l MC.DampFL.Frc MC.DampFR.Frc MC.DampRL.Frc MC.DampRR.Frc MC.DampFL.v MC.DampFR.v MC.DampRL.v MC.DampRR.v MC.FxFL MC.FxFR MC.FxRL MC.FxRR MC.FyFL MC.FyFR MC.FyRL MC.FyRR MC.FzFL MC.FzFR MC.FzRL MC.FzRR MC.LongSlipFL MC.LongSlipFR MC.LongSlipRL MC.LongSlipRR MC.SlipAngleFL MC.SlipAngleFR MC.SlipAngleRL MC.SlipAngleRR MC.ToeFL MC.ToeFR MC.ToeRL MC.ToeRR MC.TrqAlignFL MC.TrqAlignFR MC.TrqAlignRL MC.TrqAlignRR Brake.pFL_FL Brake.pFR_FL Brake.pRL_FL Brake.pRR_FL Brake.Trq_FL_tot Brake.Trq_FR_tot Brake.Trq_RL_tot Brake.Trq_RR_tot PT.FL.rotv PT.FR.rotv PT.RL.rotv PT.RR.rotv PT.FL.Trq_Drive PT.FR.Trq_Drive PT.RL.Trq_Drive PT.RR.Trq_Drive PT.FL.Trq_B2W PT.FR.Trq_B2W PT.RL.Trq_B2W PT.RR.Trq_B2W
}
    QueryTimeout            {1000}
    RefQuant                {Time time T t WheelTravel.Left Implicit}
    SaveSettingsOnExit      {1}
    StartupDataWin          {1}
    WhiteDiagBackground     {0}
}
array set __graphs {
    APO.Debug               {auto	""	auto	auto}
    APO.DictMsgSize         {auto	""	auto	auto}
    APO.nQuantities         {auto	""	auto	auto}
    Brake.Hyd.Sys.pWB_RR    {Blue bar -1.0 1.0}
    Brake.Park              {auto	""	auto	auto}
    Brake.Pedal             {auto	""	auto	auto}
    Car.Aero.Frc_1.x        {auto	N	auto	auto}
    Car.Aero.Frc_1.y        {auto	N	auto	auto}
    Car.Aero.Frc_1.z        {Blue N -2333.163618164297 23.100629906523835}
    Car.Aero.Trq_1.x        {auto	Nm	auto	auto}
    Car.Aero.Trq_1.y        {auto	Nm	auto	auto}
    Car.Aero.Trq_1.z        {auto	Nm	auto	auto}
    Car.Aero.tau2_1         {auto	deg	auto	auto}
    Car.Aero.tau_1          {auto	deg	auto	auto}
    Car.Aero.vres_1.x       {auto	km/h	0	120}
    Car.Aero.vres_1.y       {auto	km/h	0	120}
    Car.Aero.vres_1.z       {auto	km/h	0	120}
    Car.BufferFL.Frc_tot    {Pink1 N -1.0 1.0}
    Car.CFL.Frc2CExt_1.y    {Blue N -688.429683227539 887.6267657470703}
    Car.CFL.Frc2CExt_1.z    {Orange N -1.0 1.0}
    Car.CFL.Frc2C_1.x       {Cyan N -1.0 1.0}
    Car.CFL.Frc2C_1.y       {Gray N -2228.721690673828 1582.9566760253906}
    Car.CFL.Frc2C_1.z       {Green1 N -2228.721690673828 1582.9566760253906}
    Car.CFL.Frc2C_2.x       {Green2 N -1.0 1.0}
    Car.CFL.Frc2C_2.y       {Green3 N -1.0 1.0}
    Car.CFL.Frc2C_2.z       {Magenta N -1.0 1.0}
    Car.CFL.Trq2C_2.x       {Blue Nm -1.0 1.0}
    Car.CFL.rz              {Blue deg -156.66991314255154 127.94022418463688}
    Car.CFR.C.v_0.x         {Gray m/s -22.89443078994751 22.97263780593872}
    Car.CFR.C.v_0.y         {Pink1 m/s -1.5316077303886413 1.367434365749359}
    Car.CFR.rz              {Blue deg -9.360273065567016 19.63682240486145}
    Car.CRL.C.v_0.x         {Pink1 m/s -25.06456811904907 28.33019884109497}
    Car.CRR.C.t_0.y         {Pink2 m -1.0 1.0}
    Car.CRR.C.v_0.x         {Pink2 m/s -22.89443078994751 22.97263780593872}
    Car.CRR.C.v_0.y         {Pink2 m/s -21.20910369873047 11.514241333007812}
    Car.CRR.Frc2C_1.x       {Cyan N -1.0 1.0}
    Car.CRR.Frc2C_1.y       {Cyan N -1.0 1.0}
    Car.CRR.Frc2C_1.z       {Blue N -1.0 1.0}
    Car.CRR.Frc2C_2.x       {Cyan N -1.0 1.0}
    Car.CRR.rx              {Cyan deg -34.26624681614006 46.676345737920144}
    Car.CRR.rz              {Gray deg -0.8212739118938085 0.6661461705954611}
    Car.CRR.tz              {Pink1 mm -7.6431496581062675 30.15474784653634}
    Car.Con.alHori          {auto	m/s^2	-10	10}
    Car.Con.atHori          {auto	m/s^2	-10	10}
    Car.Con.ax              {auto	m/s^2	-10	10}
    Car.Con.ax_1            {auto	m/s^2	-10	10}
    Car.Con.ay              {auto	m/s^2	-10	10}
    Car.Con.ay_1            {auto	m/s^2	-10	10}
    Car.Con.az              {auto	m/s^2	-10	10}
    Car.Con.az_1            {auto	m/s^2	-10	10}
    Car.Con.tx              {auto	m	auto	auto}
    Car.Con.ty              {auto	m	auto	auto}
    Car.Con.tz              {auto	m	auto	auto}
    Car.Con.v               {auto	km/h	0	120}
    Car.Con.vHori           {auto	km/h	0	120}
    Car.Con.vx_1            {auto	km/h	0	120}
    Car.Con.vy_1            {auto	km/h	0	120}
    Car.Con.vz_1            {auto	km/h	0	120}
    Car.ConA.Pitch_X        {auto	deg	auto	auto}
    Car.ConA.Roll_X         {auto	deg	auto	auto}
    Car.DampRR.Frc          {Green2 N -1.0 1.0}
    Car.Distance            {Magenta m -1.954407372515645 197.39609915124078}
    Car.Fr1.ax              {auto	m/s^2	-10	10}
    Car.Fr1.ay              {auto	m/s^2	-10	10}
    Car.Fr1.az              {auto	m/s^2	-10	10}
    Car.Fr1.rx              {auto	deg	auto	auto}
    Car.Fr1.ry              {Orange deg -1.449161455463746 2.6426609559022665}
    Car.Fr1.rz              {auto	deg	auto	auto}
    Car.Fr1.tx              {auto	m	auto	auto}
    Car.Fr1.ty              {auto	m	auto	auto}
    Car.Fr1.tz              {auto	m	auto	auto}
    Car.Fr1.vx              {auto	km/h	0	120}
    Car.Fr1.vy              {auto	km/h	0	120}
    Car.Fr1.vz              {auto	km/h	0	120}
    Car.Gen.ax              {auto	m/s^2	-10	10}
    Car.Gen.ax_1            {auto	m/s^2	-10	10}
    Car.Gen.ay              {auto	m/s^2	-10	10}
    Car.Gen.ay_1            {auto	m/s^2	-10	10}
    Car.Gen.az              {auto	m/s^2	-10	10}
    Car.Gen.az_1            {auto	m/s^2	-10	10}
    Car.Gen.tx              {auto	m	auto	auto}
    Car.Gen.ty              {auto	m	auto	auto}
    Car.Gen.tz              {auto	m	auto	auto}
    Car.Gen.vx_1            {auto	km/h	0	120}
    Car.Gen.vy_1            {auto	km/h	0	120}
    Car.Gen.vz_1            {auto	km/h	0	120}
    Car.Hitch.Frc2Car.x     {auto	N	auto	auto}
    Car.Hitch.Frc2Car.y     {auto	N	auto	auto}
    Car.Hitch.Frc2Car.z     {auto	N	auto	auto}
    Car.Hitch.Trq2Car.x     {auto	Nm	auto	auto}
    Car.Hitch.Trq2Car.y     {auto	Nm	auto	auto}
    Car.Hitch.Trq2Car.z     {auto	Nm	auto	auto}
    Car.Hitch.tx            {auto	m	auto	auto}
    Car.Hitch.ty            {auto	m	auto	auto}
    Car.Hitch.tz            {auto	m	auto	auto}
    Car.Hitch.vx            {Blue km/h 0.0 120.0}
    Car.Hitch.vy            {auto	km/h	0	120}
    Car.Hitch.vz            {auto	km/h	0	120}
    Car.Jack.FzFL           {auto	N	auto	auto}
    Car.Jack.FzFR           {auto	N	auto	auto}
    Car.Jack.FzRL           {auto	N	auto	auto}
    Car.Jack.FzRR           {auto	N	auto	auto}
    Car.Jack.tzFL           {auto	m	auto	auto}
    Car.Jack.tzFR           {auto	m	auto	auto}
    Car.Jack.tzRL           {auto	m	auto	auto}
    Car.Jack.tzRR           {auto	m	auto	auto}
    Car.KinPitchCenter_L.x  {auto	m	auto	auto}
    Car.KinPitchCenter_L.x_1 {auto	m	auto	auto}
    Car.KinPitchCenter_L.y_1 {auto	m	auto	auto}
    Car.KinPitchCenter_L.z  {auto	m	auto	auto}
    Car.KinPitchCenter_L.z_1 {auto	m	auto	auto}
    Car.KinPitchCenter_R.x  {auto	m	auto	auto}
    Car.KinPitchCenter_R.x_1 {auto	m	auto	auto}
    Car.KinPitchCenter_R.y_1 {auto	m	auto	auto}
    Car.KinPitchCenter_R.z  {auto	m	auto	auto}
    Car.KinPitchCenter_R.z_1 {auto	m	auto	auto}
    Car.Load.0.mass         {auto	kg	auto	auto}
    Car.Load.0.tx           {auto	m	auto	auto}
    Car.Load.0.ty           {auto	m	auto	auto}
    Car.Load.0.tz           {auto	m	auto	auto}
    Car.Load.1.mass         {auto	kg	auto	auto}
    Car.Load.1.tx           {auto	m	auto	auto}
    Car.Load.1.ty           {auto	m	auto	auto}
    Car.Load.1.tz           {auto	m	auto	auto}
    Car.Load.2.mass         {auto	kg	auto	auto}
    Car.Load.2.tx           {auto	m	auto	auto}
    Car.Load.2.ty           {auto	m	auto	auto}
    Car.Load.2.tz           {auto	m	auto	auto}
    Car.Load.3.mass         {auto	kg	auto	auto}
    Car.Load.3.tx           {auto	m	auto	auto}
    Car.Load.3.ty           {auto	m	auto	auto}
    Car.Load.3.tz           {auto	m	auto	auto}
    Car.LongSlipFR          {Green3 {} -0.020042550303041935 0.8721184660866856}
    Car.LongSlipRL          {Cyan {} -0.029407467524288224 3.090936783183133}
    Car.LongSlipRR          {Blue {} -0.029407467524288224 3.090936783183133}
    Car.Pitch               {auto	deg	auto	auto}
    Car.PitchAcc            {auto	deg/s^2	auto	auto}
    Car.PitchVel            {auto	deg/s	auto	auto}
    Car.Road.GCS.Elev       {auto	m	auto	auto}
    Car.Road.GCS.Lat        {auto	deg	auto	auto}
    Car.Road.GCS.Long       {auto	deg	auto	auto}
    Car.Road.JuncId         {auto	""	auto	auto}
    Car.Road.Lane.Act.LaneId {auto	""	auto	auto}
    Car.Road.Lane.Act.Type  {auto	""	auto	auto}
    Car.Road.Lane.Act.Width {auto	m	auto	auto}
    Car.Road.Lane.Act.isRight {auto	""	auto	auto}
    Car.Road.Lane.Act.tMidLane {auto	m	auto	auto}
    Car.Road.Lane.OnLeft.LaneId {auto	""	auto	auto}
    Car.Road.Lane.OnLeft.Type {auto	""	auto	auto}
    Car.Road.Lane.OnLeft.Width {auto	m	auto	auto}
    Car.Road.Lane.OnLeft.isRight {auto	""	auto	auto}
    Car.Road.Lane.OnLeft.tMidLane {auto	m	auto	auto}
    Car.Road.Lane.OnRight.LaneId {auto	""	auto	auto}
    Car.Road.Lane.OnRight.Type {auto	""	auto	auto}
    Car.Road.Lane.OnRight.Width {auto	m	auto	auto}
    Car.Road.Lane.OnRight.isRight {auto	""	auto	auto}
    Car.Road.Lane.OnRight.tMidLane {auto	m	auto	auto}
    Car.Road.Lane.nLeft     {auto	""	auto	auto}
    Car.Road.Lane.nRight    {auto	""	auto	auto}
    Car.Road.LinkId         {auto	""	auto	auto}
    Car.Road.Path.DevAng    {auto	deg	auto	auto}
    Car.Road.Path.DevDist   {auto	m	auto	auto}
    Car.Road.Path.LatSlope  {auto	deg	auto	auto}
    Car.Road.Path.LongSlope {auto	deg	auto	auto}
    Car.Road.Route.DevAng   {auto	deg	auto	auto}
    Car.Road.Route.DevDist  {auto	m	auto	auto}
    Car.Road.Route.LatSlope {auto	deg	auto	auto}
    Car.Road.Route.LongSlope {auto	deg	auto	auto}
    Car.Road.nextJuncId     {auto	""	auto	auto}
    Car.Road.onJunction     {auto	""	auto	auto}
    Car.Road.s2lastJunc     {auto	m	auto	auto}
    Car.Road.s2nextJunc     {auto	m	auto	auto}
    Car.Road.sRoad          {auto	m	auto	auto}
    Car.Road.tx             {auto	m	auto	auto}
    Car.Road.ty             {auto	m	auto	auto}
    Car.Road.tz             {auto	m	auto	auto}
    Car.Roll                {auto	deg	auto	auto}
    Car.RollAcc             {auto	deg/s^2	auto	auto}
    Car.RollKin_F           {auto	deg	auto	auto}
    Car.RollKin_R           {auto	deg	auto	auto}
    Car.RollVel             {auto	deg/s	auto	auto}
    Car.SideSlipAngle       {Red deg -1.9090857198711388 0.9305769954123371}
    Car.SideSlipAngle2      {auto	deg	auto	auto}
    Car.SideSlipAngleVel    {auto	deg/s	auto	auto}
    Car.SimPhase            {auto	""	auto	auto}
    Car.SlipAngleFR         {Magenta deg -10.082749987075598 19.161030478693046}
    Car.SlipAngleRR         {Pink2 deg -4.48226980483773 7.367708918877841}
    Car.SlotCar.Deviation   {auto	m	auto	auto}
    Car.SlotCar.State       {auto	""	auto	auto}
    Car.StandbyMode         {auto	""	auto	auto}
    Car.TrackCurv           {auto	1/m	auto	auto}
    Car.TrackRadius         {auto	m	auto	auto}
    Car.Virtual.Frc_0.x     {auto	N	auto	auto}
    Car.Virtual.Frc_0.y     {auto	N	auto	auto}
    Car.Virtual.Frc_0.z     {auto	N	auto	auto}
    Car.Virtual.Frc_1.x     {auto	N	auto	auto}
    Car.Virtual.Frc_1.y     {auto	N	auto	auto}
    Car.Virtual.Frc_1.z     {auto	N	auto	auto}
    Car.Virtual.Trq_0.x     {auto	Nm	auto	auto}
    Car.Virtual.Trq_0.y     {auto	Nm	auto	auto}
    Car.Virtual.Trq_0.z     {auto	Nm	auto	auto}
    Car.Virtual.Trq_1.x     {auto	Nm	auto	auto}
    Car.Virtual.Trq_1.y     {auto	Nm	auto	auto}
    Car.Virtual.Trq_1.z     {auto	Nm	auto	auto}
    Car.WheelSpd_RR         {Pink2 rad/s -1.0 1.0}
    Car.WheelTurnSpd_RR     {Pink2 rad/s -1.0 1.0}
    Car.Yaw                 {auto	deg	auto	auto}
    Car.YawAcc              {auto	deg/s^2	auto	auto}
    Car.YawRate             {Green3 deg/s -73.2660301208496 67.17859725952148}
    Car.YawVel              {auto	deg/s	auto	auto}
    Car.alHori              {auto	m/s^2	-10	10}
    Car.atHori              {auto	m/s^2	-10	10}
    Car.ax                  {Blue m/s^2 -9.823345127105712 11.64188570022583}
    Car.ay                  {Red m/s^2 -13.20484769821167 10.645408992767335}
    Car.az                  {Gray m/s^2 -15.535589513778687 10.851489362716675}
    Car.tx                  {auto	m	auto	auto}
    Car.ty                  {auto	m	auto	auto}
    Car.tz                  {auto	m	auto	auto}
    Car.v                   {Green1 km/h -1.1902421556866938 120.21773235561068}
    Car.vx                  {Cyan km/h 0.0 120.0}
    Car.vxFR                {Green1 m/s -0.22514743804931642 22.739891242980956}
    Car.vxRR                {White m/s 7.37434458101713 25.04782078552246}
    Car.vy                  {Blue km/h 0.0 120.0}
    Car.vyFR                {Gray m/s -2.819289469718933 5.62370183467865}
    Car.vyRR                {Green2 m/s -2.819289469718933 5.62370183467865}
    Car.vz                  {auto	km/h	0	120}
    DM.Brake                {auto	""	0	1.2}
    DM.BrakePark            {auto	""	0	1.2}
    DM.Clutch               {auto	""	0	1.2}
    DM.Gas                  {auto	""	0	1.2}
    DM.GearNo               {auto	""	0	1.2}
    DM.GearNo.Trgt          {auto	""	0	1.2}
    DM.Handbrake            {auto	""	0	1.2}
    DM.Key                  {auto	""	0	1.2}
    DM.LaneOffset           {auto	m	auto	auto}
    DM.Lap.No               {auto	""	0	1.2}
    DM.Lap.Time             {auto	s	auto	auto}
    DM.Lights.FogFront      {auto	""	0	1.2}
    DM.Lights.FogRear       {auto	""	0	1.2}
    DM.Lights.Hazard        {auto	""	0	1.2}
    DM.Lights.HighBeam      {auto	""	0	1.2}
    DM.Lights.Indicator     {auto	""	0	1.2}
    DM.Lights.MainLight     {auto	""	0	1.2}
    DM.ManDist              {auto	m	auto	auto}
    DM.ManNo                {auto	""	0	1.2}
    DM.ManTime              {auto	s	auto	auto}
    DM.OperationState_trg   {auto	""	0	1.2}
    DM.OperatorActive       {auto	""	0	1.2}
    DM.SST                  {auto	""	0	1.2}
    DM.SelectorCtrl         {auto	""	0	1.2}
    DM.Shifting             {auto	""	0	1.2}
    DM.SpeedLimit           {auto	m/s	auto	auto}
    DM.SpeedOffset          {auto	m/s	auto	auto}
    DM.Steer.Ang            {auto	deg	auto	auto}
    DM.Steer.AngAcc         {auto	deg/s^2	auto	auto}
    DM.Steer.AngVel         {auto	deg/s	auto	auto}
    DM.Steer.SinusFreq      {auto	Hz	auto	auto}
    DM.Steer.Trq            {auto	Nm	auto	auto}
    DM.SteerBy              {auto	""	0	1.2}
    DM.StopDist             {auto	m	auto	auto}
    DM.StopTime             {auto	s	auto	auto}
    DM.TriggerPoint.Dist    {auto	m	auto	auto}
    DM.TriggerPoint.Id      {auto	""	0	1.2}
    DM.TriggerPoint.Time    {auto	s	auto	auto}
    DM.UserSignal_0         {auto	""	0	1.2}
    DM.UserSignal_1         {auto	""	0	1.2}
    DM.UserSignal_2         {auto	""	0	1.2}
    DM.UserSignal_3         {auto	""	0	1.2}
    DM.UserSignal_4         {auto	""	0	1.2}
    DM.ax.Trgt              {auto	m/s^2	auto	auto}
    DM.v.Trgt               {auto	km/h	0	120}
    DM.v.Trgt_LimitHi       {auto	km/h	0	120}
    DM.v.Trgt_LimitLo       {auto	km/h	0	120}
    DM.vdelta.Trgt          {auto	km/h	0	120}
    DeltaT                  {auto	s	auto	auto}
    DeltaTPeak              {auto	s	auto	auto}
    Driver.Adapt.Phase      {auto	""	auto	auto}
    Driver.Brake            {auto	""	auto	auto}
    Driver.BrakeLever       {auto	""	auto	auto}
    Driver.BrakeLever_UDrvIn {auto	""	auto	auto}
    Driver.BrakePark        {auto	""	auto	auto}
    Driver.BrakePark_UDrvIn {auto	""	auto	auto}
    Driver.Brake_UDrvIn     {auto	""	auto	auto}
    Driver.Clutch           {auto	""	auto	auto}
    Driver.Clutch_UDrvIn    {auto	""	auto	auto}
    Driver.Gas              {Green3 {} -0.01 1.01}
    Driver.Gas_UDrvIn       {auto	""	auto	auto}
    Driver.GearNo           {auto	""	auto	auto}
    Driver.GearNoTrgt       {auto	""	auto	auto}
    Driver.GearNo_UDrvIn    {auto	""	auto	auto}
    Driver.Lat.dy           {auto	m	auto	auto}
    Driver.Lat.passive      {auto	""	auto	auto}
    Driver.Long.dv          {auto	m/s	auto	auto}
    Driver.Long.passive     {auto	""	auto	auto}
    Driver.ReCon.ADAS_LD_Coef {auto	""	auto	auto}
    Driver.ReCon.ADAS_LD_T  {auto	""	auto	auto}
    Driver.ReCon.Accel      {auto	m/s^2	auto	auto}
    Driver.ReCon.Decel      {auto	m/s^2	auto	auto}
    Driver.ReCon.DriveChar.CF_GGExp {auto	""	auto	auto}
    Driver.ReCon.DriveChar.CF_axy {auto	""	auto	auto}
    Driver.ReCon.DriveChar.iChange {auto	""	auto	auto}
    Driver.ReCon.DriveMode  {auto	""	auto	auto}
    Driver.ReCon.JunDir     {auto	""	auto	auto}
    Driver.ReCon.Speed      {auto	km/h	auto	auto}
    Driver.ReCon.StopDist   {auto	m	auto	auto}
    Driver.ReCon.StopTask   {auto	""	auto	auto}
    Driver.ReCon.StopTime   {auto	s	auto	auto}
    Driver.ReCon.Task       {auto	""	auto	auto}
    Driver.ReCon.Task_lat   {auto	""	auto	auto}
    Driver.ReCon.Trf_Consider {auto	""	auto	auto}
    Driver.ReCon.Trf_FOL.ObjId {auto	""	auto	auto}
    Driver.ReCon.Trf_FOL.Targ_Dtct {auto	""	auto	auto}
    Driver.ReCon.Trf_FOL.dDist {auto	m	auto	auto}
    Driver.ReCon.Trf_FOL.dSpeed {auto	m/s	auto	auto}
    Driver.ReCon.Trf_ONC.ObjId {auto	""	auto	auto}
    Driver.ReCon.Trf_ONC.Targ_Dtct {auto	""	auto	auto}
    Driver.ReCon.Trf_ONC.dDist {auto	m	auto	auto}
    Driver.ReCon.Trf_ONC.dSpeed {auto	m/s	auto	auto}
    Driver.ReCon.Trf_OTR.ObjId {auto	""	auto	auto}
    Driver.ReCon.Trf_OTR.Targ_Dtct {auto	""	auto	auto}
    Driver.ReCon.Trf_OTR.dDist {auto	m	auto	auto}
    Driver.ReCon.Trf_OTR.dSpeed {auto	m/s	auto	auto}
    Driver.ReCon.Trf_Overtake {auto	""	auto	auto}
    Driver.ReCon.Trf_Overtake_LaneOffset {auto	m	auto	auto}
    Driver.SelectorCtrl     {auto	""	auto	auto}
    Driver.SetGearNo        {auto	""	auto	auto}
    Driver.Shifting         {auto	""	auto	auto}
    Driver.Steer.Ang        {auto	deg	auto	auto}
    Driver.Steer.AngAcc     {auto	deg/s^2	auto	auto}
    Driver.Steer.AngVel     {auto	deg/s	auto	auto}
    Driver.Steer.Trq        {auto	Nm	auto	auto}
    Driver.UDrv.Active      {auto	""	auto	auto}
    Driver.WaitFlag         {auto	""	auto	auto}
    Env.AirDensity          {auto	kg/m^3	auto	auto}
    Env.AirHumidity         {auto	""	auto	auto}
    Env.AirPressure         {auto	bar	auto	auto}
    Env.RainRate            {auto	mm/h	auto	auto}
    Env.SolarRadiation      {auto	W/m^2	auto	auto}
    Env.Temperature         {auto	K	auto	auto}
    Env.Time                {auto	hours	auto	auto}
    Env.VisRangeInFog       {auto	m	auto	auto}
    Env.WindVel_ext.x       {auto	m/s	auto	auto}
    Env.WindVel_ext.y       {auto	m/s	auto	auto}
    Env.WindVel_ext.z       {auto	m/s	auto	auto}
    Env.WindVel_tot.x       {auto	m/s	auto	auto}
    Env.WindVel_tot.y       {auto	m/s	auto	auto}
    Env.WindVel_tot.z       {auto	m/s	auto	auto}
    Env.YearDay             {auto	days	auto	auto}
    Log.nError              {auto	""	auto	auto}
    Log.nLog                {auto	""	auto	auto}
    Log.nWarn               {auto	""	auto	auto}
    PT.BCU.SOC_HV           {Cyan % -1.0 1.0}
    PT.BattHV.Current       {Magenta A -18.942047672271727 272.41056688308714}
    PT.Control.Ignition     {auto	""	auto	auto}
    PT.Control.OperationError {auto	""	auto	auto}
    PT.Control.OperationState {auto	""	auto	auto}
    PT.DL.iDiff_mean        {auto	""	auto	auto}
    PT.Engine.rotv          {auto	rpm	0	7000}
    PT.GearBox.GearNo       {auto	""	auto	auto}
    PT.Motor.Trq            {Gray Nm -16.841939048767088 48.635766105651854}
    PT.Motor1.Trq           {Pink2 Nm -3.8607868647575376 22.12584943532944}
    PT.Motor1.rot           {Gray rad -1.0 1.0}
    PT.Motor1.rotv          {Green2 rpm -110.29185028147823 11139.53061372849}
    PT.Motor2.Trq           {Pink1 Nm 1.0210374748706819 16.38940547347069}
    PT.Motor3.Trq           {Orange Nm 3.3228470277786255 48.36154256343841}
    PT.Motor3.rotv          {Green3 rpm -9.549296596425384 9.549296596425384}
    PT.PwrSupply.HV1.Pwr    {White W -487.2225390625 64509.4764453125}
    PT.PwrSupply.HV1.Voltage {Orange V 309.04483673095706 387.0974667358398}
    PT.Trq_Supp2Bdy1.y      {auto	Nm	auto	auto}
    PT.Trq_Supp2Bdy1B.y     {auto	Nm	auto	auto}
    PT.Trq_Supp2BdyEng.x    {auto	Nm	auto	auto}
    PT.Trq_Supp2BdyEng.y    {auto	Nm	auto	auto}
    PT.VDCU.Alfa_FR         {Pink1 deg -10.082749987075598 19.161030478693046}
    PT.VDCU.Alfa_RR         {Pink2 deg -15.282536334991455 20.586645908355713}
    PT.VDCU.Beta            {Blue deg -116.58201217651367 -95.58913803100586}
    PT.VDCU.Body_Speed_Ref  {Cyan m/s 12.731759071350098 13.158989906311035}
    PT.VDCU.Delta           {Red deg -8.974910802263528 23.277523116965288}
    PT.VDCU.Ref_YawRate     {Green1 deg/s -73.2660301208496 67.17859725952148}
    PT.VDCU.VelX_FR         {Yellow m/s -1.5316077303886413 1.367434365749359}
    PT.VDCU.VelX_RR         {Cyan m/s 7.37434458101713 25.04782078552246}
    PT.VDCU.VelY_FR         {Green1 m/s -2.819289469718933 5.62370183467865}
    PT.VDCU.VelY_RR         {Green3 m/s -2.819289469718933 5.62370183467865}
    PT.VDCU.Yaw_Trq_applied {Magenta Nm -26.102879524230957 48.652886390686035}
    PT.VDCU.r_FR            {Orange deg -1.0 1.0}
    SC.MemFree              {auto	Byte	auto	auto}
    SC.MemUsed              {auto	Byte	auto	auto}
    SC.MemUsed.TRNo         {auto	""	auto	auto}
    SC.SimLoad.Mode         {auto	""	auto	auto}
    SC.SimLoad.Time         {auto	ms	auto	auto}
    SC.Start.No             {auto	""	auto	auto}
    SC.State                {auto	""	auto	auto}
    SC.TAccel               {auto	""	auto	auto}
    Steer.AssistFrc         {auto	N	auto	auto}
    Steer.AssistFrc_Ext     {auto	N	auto	auto}
    Steer.AssistTrqCol      {auto	Nm	auto	auto}
    Steer.AssistTrqCol_Ext  {auto	Nm	auto	auto}
    Steer.AssistTrqPin      {auto	Nm	auto	auto}
    Steer.AssistTrqPin_Ext  {auto	Nm	auto	auto}
    Steer.Cfg.PosSign       {auto	""	auto	auto}
    Steer.L.iSteer2q        {auto	m/deg	auto	auto}
    Steer.L.q               {auto	m	auto	auto}
    Steer.L.qp              {auto	m/s	auto	auto}
    Steer.L.qpp             {auto	m/s^2	auto	auto}
    Steer.R.iSteer2q        {auto	m/deg	auto	auto}
    Steer.R.q               {auto	m	auto	auto}
    Steer.R.qp              {auto	m/s	auto	auto}
    Steer.R.qpp             {auto	m/s^2	auto	auto}
    Steer.RL.q              {Green1	m	auto	auto}
    Steer.RL.qp             {Green1	m/s	auto	auto}
    Steer.RR.q              {Blue	m	auto	auto}
    Steer.RR.qp             {Blue	m/s	auto	auto}
    Steer.SteerBy           {auto	""	auto	auto}
    Steer.WhlAcc            {auto	deg/s^2	auto	auto}
    Steer.WhlAng            {Cyan deg -99.96272581412072 101.92324971150794}
    Steer.WhlTrq            {auto	Nm	auto	auto}
    Steer.WhlTrqStatic      {auto	Nm	auto	auto}
    Steer.WhlVel            {auto	deg/s	auto	auto}
    TCPU.AposEvalSend       {auto	ms	0	1.2}
    TCPU.AposPoll           {auto	ms	0	1.2}
    TCPU.Brake              {auto	ms	0	1.2}
    TCPU.Cycle              {auto	ms	0	1.2}
    TCPU.DrivMan            {auto	ms	0	1.2}
    TCPU.In                 {auto	ms	0	1.2}
    TCPU.Out                {auto	ms	0	1.2}
    TCPU.PowerTrain         {auto	ms	0	1.2}
    TCPU.Sensors            {auto	ms	0	1.2}
    TCPU.Total              {auto	ms	0	1.2}
    TCPU.Traffic            {auto	ms	0	1.2}
    TCPU.Trailer            {auto	ms	0	1.2}
    TCPU.User               {auto	ms	0	1.2}
    TCPU.Vehicle            {auto	ms	0	1.2}
    TCPU.VehicleControl     {auto	ms	0	1.2}
    Time                    {auto	s	auto	auto}
    Time.Global             {auto	s	auto	auto}
    Time.WC                 {Blue s 73.7208792520578 74.0066004863502}
    UserOut_00              {auto	""	auto	auto}
    UserOut_01              {auto	""	auto	auto}
    UserOut_02              {auto	""	auto	auto}
    UserOut_03              {auto	""	auto	auto}
    UserOut_04              {auto	""	auto	auto}
    UserOut_05              {auto	""	auto	auto}
    UserOut_06              {auto	""	auto	auto}
    UserOut_07              {auto	""	auto	auto}
    UserOut_08              {auto	""	auto	auto}
    UserOut_09              {auto	""	auto	auto}
    VC.Brake                {auto	""	auto	auto}
    VC.BrakePark            {auto	""	auto	auto}
    VC.Clutch               {auto	""	auto	auto}
    VC.Gas                  {Red {} -0.01 1.01}
    VC.GearNo               {auto	""	auto	auto}
    VC.Key                  {auto	""	auto	auto}
    VC.Lights.Brake         {auto	""	auto	auto}
    VC.Lights.Daytime       {auto	""	auto	auto}
    VC.Lights.FogFrontL     {auto	""	auto	auto}
    VC.Lights.FogFrontR     {auto	""	auto	auto}
    VC.Lights.FogRear       {auto	""	auto	auto}
    VC.Lights.HighBeam      {auto	""	auto	auto}
    VC.Lights.IndL          {auto	""	auto	auto}
    VC.Lights.IndR          {auto	""	auto	auto}
    VC.Lights.LowBeam       {auto	""	auto	auto}
    VC.Lights.ParkL         {auto	""	auto	auto}
    VC.Lights.ParkR         {auto	""	auto	auto}
    VC.Lights.Reverse       {auto	""	auto	auto}
    VC.Lights.bm            {auto	""	auto	auto}
    VC.SST                  {auto	""	auto	auto}
    VC.SelectorCtrl         {auto	""	auto	auto}
    VC.Steer.Ang            {Yellow deg -44.73522879910929 49.75244685624542}
    VC.Steer.AngAcc         {auto	deg/s^2	auto	auto}
    VC.Steer.AngVel         {auto	deg/s	auto	auto}
    VC.Steer.Trq            {auto	Nm	auto	auto}
    VC.UserSignal_0         {auto	""	auto	auto}
    VC.UserSignal_1         {auto	""	auto	auto}
    VC.UserSignal_2         {auto	""	auto	auto}
    VC.UserSignal_3         {auto	""	auto	auto}
    VC.UserSignal_4         {auto	""	auto	auto}
    Vhcl.Distance           {auto	m	auto	auto}
    Vhcl.Engine.rotv        {auto	deg/s	auto	auto}
    Vhcl.FL.Fx              {White	N	auto	auto}
    Vhcl.FL.Fy              {White	N	auto	auto}
    Vhcl.FL.Fz              {White N -20.81336181640625 2102.149543457031}
    Vhcl.FL.LongSlip        {Blue {} -0.008442262294702232 0.09078377170022577}
    Vhcl.FL.SideSlip        {White deg -34.26624681614006 46.676345737920144}
    Vhcl.FL.Trq_B2WC        {White	Nm	auto	auto}
    Vhcl.FL.Trq_Brake       {White	Nm	auto	auto}
    Vhcl.FL.Trq_DL2WC       {White	Nm	auto	auto}
    Vhcl.FL.Trq_Drive       {Green3 Nm -2.6703912353151136 269.70951477050744}
    Vhcl.FL.Trq_T2W         {White	Nm	auto	auto}
    Vhcl.FL.Trq_WhlBearing  {White	Nm	auto	auto}
    Vhcl.FL.rot             {White	deg	auto	auto}
    Vhcl.FL.rotv            {White	deg/s	auto	auto}
    Vhcl.FL.rx              {White	deg	auto	auto}
    Vhcl.FL.ry              {White	deg	auto	auto}
    Vhcl.FL.rz              {White	deg	auto	auto}
    Vhcl.FL.tx              {White	m	auto	auto}
    Vhcl.FL.ty              {White	m	auto	auto}
    Vhcl.FL.tz              {White	m	auto	auto}
    Vhcl.FL.vBelt           {White	km/h	0	120}
    Vhcl.FR.Fx              {Red	N	auto	auto}
    Vhcl.FR.Fy              {Red	N	auto	auto}
    Vhcl.FR.Fz              {White N 209.07760986328125 2137.8166772460936}
    Vhcl.FR.LongSlip        {Cyan {} -0.0007647752365301131 0.06592518580982869}
    Vhcl.FR.SideSlip        {White deg -15.282536334991455 20.586645908355713}
    Vhcl.FR.Trq_B2WC        {Red	Nm	auto	auto}
    Vhcl.FR.Trq_Brake       {Red	Nm	auto	auto}
    Vhcl.FR.Trq_DL2WC       {Red	Nm	auto	auto}
    Vhcl.FR.Trq_Drive       {Red	Nm	auto	auto}
    Vhcl.FR.Trq_T2W         {Red	Nm	auto	auto}
    Vhcl.FR.Trq_WhlBearing  {Red	Nm	auto	auto}
    Vhcl.FR.rot             {Red	deg	auto	auto}
    Vhcl.FR.rotv            {Red	deg/s	auto	auto}
    Vhcl.FR.rx              {Red	deg	auto	auto}
    Vhcl.FR.ry              {Red	deg	auto	auto}
    Vhcl.FR.rz              {Purple deg -20.19717699168393 20.758474850996716}
    Vhcl.FR.tx              {Red	m	auto	auto}
    Vhcl.FR.ty              {Red	m	auto	auto}
    Vhcl.FR.tz              {Red m -1.0 1.0}
    Vhcl.FR.vBelt           {Red	km/h	0	120}
    Vhcl.Fr1.x              {auto	m	auto	auto}
    Vhcl.Fr1.y              {auto	m	auto	auto}
    Vhcl.Fr1.z              {Pink2 mm -36.34389506240089 -25.978859702581065}
    Vhcl.Fr1B.rx            {auto	deg	auto	auto}
    Vhcl.Fr1B.ry            {auto	deg	auto	auto}
    Vhcl.GearNo             {auto	""	auto	auto}
    Vhcl.Hitch.x            {auto	m	auto	auto}
    Vhcl.Hitch.y            {auto	m	auto	auto}
    Vhcl.Hitch.z            {auto	m	auto	auto}
    Vhcl.Ignition           {auto	""	auto	auto}
    Vhcl.OperationError     {auto	""	auto	auto}
    Vhcl.OperationState     {auto	""	auto	auto}
    Vhcl.Pitch              {auto	deg	auto	auto}
    Vhcl.PitchAcc           {auto	deg/s^2	auto	auto}
    Vhcl.PitchVel           {auto	deg/s	auto	auto}
    Vhcl.PoI.GCS.Elev       {auto	m	auto	auto}
    Vhcl.PoI.GCS.Lat        {auto	deg	auto	auto}
    Vhcl.PoI.GCS.Long       {auto	deg	auto	auto}
    Vhcl.PoI.ax             {auto	m/s^2	auto	auto}
    Vhcl.PoI.ax_1           {auto	m/s^2	auto	auto}
    Vhcl.PoI.ay             {auto	m/s^2	auto	auto}
    Vhcl.PoI.ay_1           {auto	m/s^2	auto	auto}
    Vhcl.PoI.az             {auto	m/s^2	auto	auto}
    Vhcl.PoI.az_1           {auto	m/s^2	auto	auto}
    Vhcl.PoI.vx             {Blue km/h -92.34746559956868 12.774759631427534}
    Vhcl.PoI.vx_1           {auto	km/h	0	120}
    Vhcl.PoI.vy             {Cyan km/h -92.34746559956868 12.774759631427534}
    Vhcl.PoI.vy_1           {auto	km/h	0	120}
    Vhcl.PoI.vz             {auto	km/h	0	120}
    Vhcl.PoI.vz_1           {auto	km/h	0	120}
    Vhcl.PoI.x              {Green2 m -1.0 1.0}
    Vhcl.PoI.y              {Gray m -1.0 1.0}
    Vhcl.PoI.z              {auto	m	auto	auto}
    Vhcl.RL.Fx              {Green1	N	auto	auto}
    Vhcl.RL.FxTwin          {Green1	N	auto	auto}
    Vhcl.RL.Fy              {Green1	N	auto	auto}
    Vhcl.RL.FyTwin          {Green1	N	auto	auto}
    Vhcl.RL.Fz              {Green1 N -20.81336181640625 2102.149543457031}
    Vhcl.RL.FzTwin          {Green1	N	auto	auto}
    Vhcl.RL.LongSlip        {Orange {} -0.008442262294702232 0.09078377170022577}
    Vhcl.RL.SideSlip        {Green1 deg -34.26624681614006 46.676345737920144}
    Vhcl.RL.Trq_B2WC        {Green1	Nm	auto	auto}
    Vhcl.RL.Trq_Brake       {Green1	Nm	auto	auto}
    Vhcl.RL.Trq_DL2WC       {Green1	Nm	auto	auto}
    Vhcl.RL.Trq_Drive       {Green1 Nm -2.6703912353151136 269.70951477050744}
    Vhcl.RL.Trq_T2W         {Green1	Nm	auto	auto}
    Vhcl.RL.Trq_WhlBearing  {Green1	Nm	auto	auto}
    Vhcl.RL.rot             {Green1	deg	auto	auto}
    Vhcl.RL.rotv            {Green1	deg/s	auto	auto}
    Vhcl.RL.rx              {Green1	deg	auto	auto}
    Vhcl.RL.ry              {Green1	deg	auto	auto}
    Vhcl.RL.rz              {Pink1 deg -18.632944831848146 20.74298740386963}
    Vhcl.RL.tx              {Green1	m	auto	auto}
    Vhcl.RL.ty              {Green1	m	auto	auto}
    Vhcl.RL.tz              {Green1	m	auto	auto}
    Vhcl.RL.vBelt           {Green1	km/h	0	120}
    Vhcl.RR.Fx              {Blue	N	auto	auto}
    Vhcl.RR.FxTwin          {Blue	N	auto	auto}
    Vhcl.RR.Fy              {Blue	N	auto	auto}
    Vhcl.RR.FyTwin          {Blue	N	auto	auto}
    Vhcl.RR.Fz              {White N 0.7471891593933101 1956.4054197120668}
    Vhcl.RR.FzTwin          {Blue	N	auto	auto}
    Vhcl.RR.LongSlip        {Blue {} -0.012763571329414844 0.030518230386078357}
    Vhcl.RR.SideSlip        {Yellow deg -4.48226980483773 7.367708918877841}
    Vhcl.RR.Trq_B2WC        {Blue	Nm	auto	auto}
    Vhcl.RR.Trq_Brake       {Blue	Nm	auto	auto}
    Vhcl.RR.Trq_DL2WC       {Blue	Nm	auto	auto}
    Vhcl.RR.Trq_Drive       {Blue	Nm	auto	auto}
    Vhcl.RR.Trq_T2W         {Blue	Nm	auto	auto}
    Vhcl.RR.Trq_WhlBearing  {Blue	Nm	auto	auto}
    Vhcl.RR.rot             {Blue	deg	auto	auto}
    Vhcl.RR.rotv            {Blue deg/s -57.295779512896175 57.295779512896175}
    Vhcl.RR.rx              {Blue	deg	auto	auto}
    Vhcl.RR.ry              {Blue	deg	auto	auto}
    Vhcl.RR.rz              {Blue	deg	auto	auto}
    Vhcl.RR.tx              {Blue	m	auto	auto}
    Vhcl.RR.ty              {Blue	m	auto	auto}
    Vhcl.RR.tz              {Blue	m	auto	auto}
    Vhcl.RR.vBelt           {Blue	km/h	0	120}
    Vhcl.Roll               {auto	deg	auto	auto}
    Vhcl.RollAcc            {auto	deg/s^2	auto	auto}
    Vhcl.RollVel            {auto	deg/s	auto	auto}
    Vhcl.Steer.Acc          {auto	deg/s^2	auto	auto}
    Vhcl.Steer.Ang          {auto	deg	auto	auto}
    Vhcl.Steer.Trq          {auto	Nm	auto	auto}
    Vhcl.Steer.Vel          {auto	deg/s	auto	auto}
    Vhcl.Wind.vx            {auto	km/h	0	120}
    Vhcl.Wind.vy            {auto	km/h	0	120}
    Vhcl.Wind.vz            {auto	km/h	0	120}
    Vhcl.Yaw                {auto	deg	auto	auto}
    Vhcl.YawAcc             {auto	deg/s^2	auto	auto}
    Vhcl.YawRate            {auto	deg/s	auto	auto}
    Vhcl.sRoad              {auto	m	auto	auto}
    Vhcl.tRoad              {auto	m	auto	auto}
    Vhcl.v                  {Gray m/s 6.239922218322754 19.95774013519287}
    default                 { colorname unit min max }
}
array set __groups {
}
array set __diagconfs {
}
